config/routes.rb
Rails.application.routes.draw do

  get "users/disconnect" => "users#disconnect"
  devise_for :users, :controllers => { :confirmations => "confirmations",
                                       :registrations => "registrations",
                                       :omniauth_callbacks => "omniauth_callbacks",
                                       :sessions => "sessions"
                                    }

  devise_scope :user do
    patch "/confirm" => "confirmations#confirm"
  end

  resources :users, :only => :none do
    get "connections"
    collection do
      get :dashboard
      get :browser_knows
      get :browser_knows_list
      get :account
      post :fetch_yodlee_data
      get :yodlee_data
      get :track_motion
    end
    get "update_contacts"
    resources :contacts do
      resources :notes
    end
  end

  resources :twillio_confirmations, only: [:new, :create] do
    collection do
      get 'check_number', as: :check_number
    end
  end

  
  root :to => "home#index"

end

app/models/note.rb
class Note < ActiveRecord::Base
	belongs_to :contact

	attr_accessible :note, :contact_id
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: [:show, :edit, :update, :destroy]
  before_action :set_user_and_contact

  # GET /notes
  # GET /notes.json
  def index
    @notes = @contact.notes.reverse
  end

  # GET /notes/1
  # GET /notes/1.json
  def show
  end

  # GET /notes/new
  def new
    @note = Note.new
  end

  # GET /notes/1/edit
  def edit
  end

  # POST /notes
  # POST /notes.json
  def create
    @note = Note.new(note_params)

    respond_to do |format|
      if @note.save
        format.html { redirect_to user_contact_notes_path, notice: 'Note was successfully created.' }
        format.json { render action: 'show', status: :created, location: @note }
      else
        format.html { render action: 'new' }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notes/1
  # PATCH/PUT /notes/1.json
  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to @note, notice: 'Note was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.json
  def destroy
    @note.destroy
    respond_to do |format|
      format.html { redirect_to notes_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = Note.find(params[:id])
    end

    def set_user_and_contact
      @user = User.find(params[:user_id])
      @contact = Contact.find(params[:contact_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def note_params
      params.require(:note).permit(:note).merge(:contact_id => params[:contact_id])
    end
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/_form.html.erb
<%= form_for([@user, @contact, @note]) do |f| %>
  <% if @note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
      <% @note.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :note %><br/>
    <%= f.text_area :note, :id => "text-area" %>
  </div>
  <br/>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/notes/edit.html.erb
<h1>Editing note</h1>

<%= render 'form' %>

<%= link_to 'Show', @note %> |
<%= link_to 'Back', notes_path %>

app/views/notes/index.html.erb
<div class="container">
		<h1>Listing Notes</h1>
	<table class="table">
		<thead>
			<tr>
				<th>Note</th>
				<th></th>
				<th>Created At</th>
				<th colspan="3"></th>
			</tr>
		</thead>

		<tbody>
			<% @notes.each do |note| %>
				<tr>
					<td><%= note.note %></td>
					<td></td>
					<td><%= note.updated_at.strftime("%B %e, %Y at %I%p") %></td>
				</tr>
			<% end %>
		</tbody>
	</table>
</div>

app/views/notes/new.html.erb
<div class="container">
	<h1>New note</h1>
	<%= render 'form' %>
	<%#= link_to 'Back', user_contact_note_path %>
</div>

app/views/notes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Note:</strong>
  <%= @note.note %>
</p>

<%= link_to 'Edit', edit_note_path(@note) %> |
<%= link_to 'Back', notes_path %>