config/routes.rb
Rails.application.routes.draw do

  get "users/disconnect" => "users#disconnect"
  devise_for :users, :controllers => { :confirmations => "confirmations",
                                       :registrations => "registrations",
                                       :omniauth_callbacks => "omniauth_callbacks",
                                       :sessions => "sessions"
                                    }

  devise_scope :user do
    patch "/confirm" => "confirmations#confirm"
  end

  resources :users, :only => :none do
    get "connections"
    collection do
      get :dashboard
      get :browser_knows
      get :browser_knows_list
      get :account
      post :fetch_yodlee_data
      get :yodlee_data
      get :track_motion
    end
    get "update_contacts"
    resources :contacts do
      resources :notes
    end
  end

  resources :twillio_confirmations, only: [:new, :create] do
    collection do
      get 'check_number', as: :check_number
    end
  end

  
  root :to => "home#index"

end

app/views/shared/_sign_up_header.html.erb
<header class="row">
    <div class="head col-sm-7">
      <img class="logo" src="/assets/logo.png" alt="">
      <ul class="top-menu" style="padding-left: 5%;">
        <li> <a data-target="#group_section_modal" data-toggle="modal" class="MainNavText" id="MainNavHelp" 
       href="#myModal">GROUPS</a> </li>
        <li>  
        <div class="dropdown">
            <a class="dropbtn">ACCOUNTS
              <i class="fa fa-caret-down"></i>
            </a>
            <div class="dropdown-content" style="width: 220px;">
              <%= link_to "My Profile", account_users_path %>
              <%= link_to "Privacy Settings", '#' %>
              <%= link_to "Advertising Settings", '#' %>
              <%= link_to "Ad Analytics",  '#'  %>
              <%= link_to "Cookies",  '#'  %>
            </div>
          </div>
        </li>
        <li> <%= link_to "DASHBOARD", dashboard_users_path %> </li>
        <li>
          <div class="dropdown">
            <a class="dropbtn">TOOLS
              <i class="fa fa-caret-down"></i>
            </a>
            <div class="dropdown-content">
              <a target= "_blank" href="http://webkay.robinlinus.com/">Webkay</a>
              <a target= "_blank" href="https://clickclickclick.click">Clickclick</a>
              <a target= "_blank" href="https://panopticlick.eff.org/">Panopticlick</a>
              <%= link_to "Browser Data", browser_knows_list_users_path %>
              <% if current_user.present? && current_user.identities.where(provider: 'yodlee').present? %>
                <%= link_to "Yodlee Data",  yodlee_data_users_path %>
              <% end %>
            </div>
          </div>
        </li>
        <li> <%= link_to "TRACK MOTION", track_motion_users_path %> </li>
      </ul>
    </div>
    <%= link_to 'Sign out', destroy_user_session_path, :method => :delete, :id=> "sign-out-btn", :class => "btn btn-primary"%>
    <div class="searcher col-sm-offset-1 col-sm-4">
      <input type="search">
      <img src="/assetssearch.png" alt="">
    </div>
</header>

app/views/shared/_twilio_modal.html.erb
<!-- <div id="loginform" class="modal" style=""> -->
 <%=  form_tag(twillio_confirmations_path, method: "post") do |f| %>
    <div class="container" style="padding-top: 10px;">
      <h1> <%= @user.phone_number%> </h1>
      <p>  We have sent you a SMS with a code to the number above. </p>
      <p> To complete your phone number verification, please enter the 6-digits activation code. </p>
    </div>
     <div class="container" style=" padding-bottom: 10px;">
       <%= label_tag :verification_code, "Verification code", class: "col-md-2 control-label" %>
       <%= text_field_tag :verification_code, nil, class: "form-control" %>
       <%= hidden_field_tag :user_id, @user.id %>
       <br><br>
       <%= submit_tag "Confirm", class: "btn btn-success" %>
       <br>
    </div>
  <% end %>
<!-- </div> -->


<script type="text/javascript">
  $(window).load(function() {
     console.log($("#loginform").modal('show'))
  });
</script>