config/routes.rb
Rails.application.routes.draw do

  get "users/disconnect" => "users#disconnect"
  devise_for :users, :controllers => { :confirmations => "confirmations",
                                       :registrations => "registrations",
                                       :omniauth_callbacks => "omniauth_callbacks",
                                       :sessions => "sessions"
                                    }

  devise_scope :user do
    patch "/confirm" => "confirmations#confirm"
  end

  resources :users, :only => :none do
    get "connections"
    collection do
      get :dashboard
      get :browser_knows
      get :browser_knows_list
      get :account
      post :fetch_yodlee_data
      get :yodlee_data
      get :track_motion
    end
    get "update_contacts"
    resources :contacts do
      resources :notes
    end
  end

  resources :twillio_confirmations, only: [:new, :create] do
    collection do
      get 'check_number', as: :check_number
    end
  end

  
  root :to => "home#index"

end

app/models/contact.rb
class Contact < ActiveRecord::Base
	before_save :default_values

	belongs_to :user
	belongs_to :identity
	has_many :notes, :dependent => :destroy

	validates :full_name, presence: true

	attr_accessible	:full_name, :first_name, :last_name, :family_name, :given_name, :photo_url, :gender,
		:network_url, :network_username, :job_title, :industry, :country, :email, :phone, :user_id,
		:identity_id, :organization, :country, :about, :notes, :education, :work

	scope :get_active_contacts, lambda { where(:is_deleted => false) }
	scope :get_deleted_contacts, lambda { where(:is_deleted => true) }
	
	def default_values
		self.photo_url = "/assets/photo.png" if (self.photo_url.nil? || self.photo_url.empty?)
		self.education = self.education.gsub("\r", "") if self.education
		self.work = self.work.gsub("\r", "") if self.work
	end

	def self.find_contact(name, network_id)
		where("full_name = ? OR google_id = ? OR facebook_id = ? OR linkedin_id = ?",name,network_id,network_id,network_id)		
	end

	def form_social_network?
		self.google_id || self.linkedin_id || self.facebook_id
	end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
	before_action :set_contact, only: [:show, :edit, :update, :destroy]
	before_action :get_user
	before_filter :authenticate_user!

	# GET /contacts
	# GET /contacts.json
	def index
		@contacts = current_user.contacts.get_active_contacts
	end

	# GET /contacts/1
	# GET /contacts/1.json
	def show
	end

	# GET /contacts/new
	def new
		@contact = Contact.new
	end

	# GET /contacts/1/edit
	def edit
	end

	# POST /contacts
	# POST /contacts.json
	def create
		@contact = Contact.new(contact_params)

		respond_to do |format|
			if @contact.save
				format.html { redirect_to user_contacts_path, notice: 'Contact was successfully created.' }
				format.json { render action: 'show', status: :created, location: @contact }
			else
				format.html { render :action => "new" }
				format.json { render json: @contact.errors, status: :unprocessable_entity }
			end
		end
	end

	# PATCH/PUT /contacts/1
	# PATCH/PUT /contacts/1.json
	def update
		respond_to do |format|
			if @contact.update(contact_params)
				format.html { redirect_to user_contact_path, notice: 'Contact was successfully updated.' }
				format.json { head :no_content }
			else
				format.html { render action: 'edit' }
				format.json { render json: @contact.errors, status: :unprocessable_entity }
			end
		end
	end

	# Soft Delete	
	def destroy
		@contact.is_deleted = true
		@contact.save!
		redirect_to user_contacts_path
	end

	private
		# Use callbacks to share common setup or constraints between actions.
		def set_contact
			@contact = Contact.find(params[:id])
		end

		def get_user
			@user = current_user
		end

		# Never trust parameters from the scary internet, only allow the white list through.
		def contact_params
			params.require(:contact).permit(:full_name, :first_name, :last_name, :given_name, :photo_url, :gender, :email, :phone, :user_id, :identity_id, :network_url, :network_username, :job_title, :organization, :industry, :country, :about, :notes, :education, :work).merge(:user_id => params[:user_id])
		end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_contact_detail.html.erb
<% if show %>
	<div class="content show" id=<%="contact_#{contact.id}"%>>
<% else %>
	<div class="content" id=<%="contact_#{contact.id}"%>>
<% end %>

	<div class="notes right-col col-sm-offset-1 col-sm-4">
		<div class="title">
			<img class="rect" src="/assetsrectangle.png" alt="">
			<h1> <%= contact.full_name.upcase %> </h1>
			<div class="mail">
				<a href=<%="mailto:#{contact.email}"%> target="_top"> <%= contact.email %> </a>
			</div>
			<% unless contact.form_social_network? %>
				<%= link_to "Edit Contact", edit_user_contact_path(:id => contact.id) %>
				&nbsp;&nbsp;&nbsp;&nbsp;
			<% end %>
			<%= link_to "Delete Contact", user_contact_path(:user_id => @user.id, :id => contact.id), method: :delete, data: { confirm: "Are you sure?" } %>
			<div class="phone">
				<%= contact.phone %>
			</div>
		</div>
		<div class="tags">
			<div class="tag">
				<img class="rounded" src="/assetsrounded_1.png" alt="">
				<h4>POKER</h4>
			</div>
			<div class="tag">
				<img class="rounded" src="/assetsrounded_2.png" alt="">
				<h4>OPERA</h4>
			</div>
			<div class="tag">
				<img class="rounded" src="/assetsrounded_3.png" alt="">
				<h4>YAHOO</h4>
			</div>
			<div class="tag">
				<img class="rounded" src="/assetsrounded_4.png" alt="">
			</div>
		</div>
		<div class="note">
			<p>
				<%= contact.notes.last.note if contact.notes.count > 0 %>
				<span class="date"><%= contact.notes.last.updated_at.strftime("%B %e, %Y at %I%p")  if contact.notes.count > 0 %></span>
			</p>
			<div class="links">
				<%= link_to "Add note", new_user_contact_note_path(:contact_id => contact.id) %>
				<%= link_to "Show all notes", user_contact_notes_path(:contact_id => contact.id) %>
			</div>
		</div>
		<div class="note">
			<h2>Work</h2>
			<p> <%= contact.work.gsub("\n", "<br/><br/>").html_safe if  contact.work %> </p>
		</div>
		<div class="note">
			<h2>Education</h2>
			<p> <%= contact.education.gsub("\n", "<br/><br/>").html_safe if contact.education %> </p>
		</div>
	</div>
</div>

app/views/contacts/_form.html.erb
<%= form_for([@user, @contact]) do |f| %>
	<% if @contact.errors.any? %>
		<div id="error_explanation">
			<h2><%= pluralize(@contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

			<ul>
			<% @contact.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
			</ul>
		</div>
	<% end %>

	<div class="field">
		<%= f.label :full_name %><br>
		<%= f.text_field :full_name %>
	</div>
	<div class="field">
		<%= f.label :first_name %><br>
		<%= f.text_field :first_name %>
	</div>
	<div class="field">
		<%= f.label :last_name %><br>
		<%= f.text_field :last_name %>
	</div>
	<div class="field">
		<%= f.label :given_name %><br>
		<%= f.text_field :given_name %>
	</div>
	<div class="field">
		<%= f.label :photo_url %><br>
		<%= f.text_field :photo_url %>
	</div>
	<div class="field">
		<%= f.label :gender %><br>
		<%= f.text_field :gender %>
	</div>
	<div class="field">
		<%= f.label :email %><br>
		<%= f.text_field :email %>
	</div>
	<div class="field">
		<%= f.label :phone %><br>
		<%= f.text_field :phone %>
	</div>
	<div class="field">
		<%= f.label :network_url %><br>
		<%= f.text_field :network_url %>
	</div>
	<div class="field">
		<%= f.label :network_username %><br>
		<%= f.text_field :network_username %>
	</div>
	<div class="field">
		<%= f.label :job_title %><br>
		<%= f.text_field :job_title %>
	</div>
	<div class="field">
		<%= f.label :organization %><br>
		<%= f.text_field :organization %>
	</div>
	<div class="field">
		<%= f.label :industry %><br>
		<%= f.text_field :industry %>
	</div>
	<div class="field">
		<%= f.label :country %><br>
		<%= f.text_field :country %>
	</div>
	<div class="field">
		<%= f.label :about %><br>
		<%= f.text_field :about %>
	</div>
	<div class="field">
		<%= f.label :education %><br>
		<%= f.text_area :education %>
	</div>
	<div class="field">
		<%= f.label :work %><br>
		<%= f.text_area :work %>
	</div>
	<br/>
	<div class="actions">
		<%= f.submit %>
	</div>
<% end %>

app/views/contacts/edit.html.erb
<div class = "container">
	<h1>Editing contact</h1>

	<%= render 'form' %>

	<%#= link_to 'Show', @contact %>
	<%#= link_to 'Back', contacts_path %>
</div>

app/views/contacts/index.html.erb
<div id="main" class="row">
	<div id="tabs_contact" class="contacts left-col col-sm-offset-1 col-sm-6">
		<% counter = 1 %>
		<% @contacts.each do |contact| %>
			<%= link_to image_tag(contact.photo_url, :class => "img-contact each#{counter}"), "#contact_#{contact.id}"%>
			<% counter = (counter % 21) + 1 %>
		<% end %>
	</div>

	<div class="notes right-col col-sm-offset-1 col-sm-4">
		<!-- <div class="btn-toolbar" >
			<%= link_to "Update Contacts", user_update_contacts_path, :class => "btn btn-success"%>
			<%= link_to "+ Add Contact", new_user_contact_path, :class => "btn btn-success"%>
		</div> -->
	</div>
	<br/><br/><br/>

	<% show = true %>
	<% @contacts.each do |contact| %>
		<%= render "contact_detail", {contact: contact, show: show} %>
		<% show = false %>
	<% end %>
</div>

app/views/contacts/new.html.erb
<div class="container">
	<h1>New contact</h1>
	<%= render 'form' %>
	<br/>
	<%= link_to 'Back to Contacts', user_contacts_path %>
</div>

app/views/contacts/show.html.erb
<div class = "container">
	
	<p> <strong>Photo:</strong> <%= link_to image_tag(@contact.photo_url), @contact.network_url %> </p>

	<p> <strong>Full Name:</strong> <%= @contact.full_name %> </p>
	<p> <strong>First name:</strong> <%= @contact.first_name %> </p>
	<p> <strong>Last name:</strong> <%= @contact.last_name %> </p>

	<p> <strong>Given name:</strong> <%= @contact.given_name %> </p>
	<p> <strong>Gender:</strong> <%= @contact.gender %> </p>

	<p> <strong>Email:</strong> <%= @contact.email %> </p>
	<p> <strong>Phone:</strong> <%= @contact.phone %> </p>

	<p> <strong>Network username:</strong> <%= @contact.network_username %> </p>
	<p> <strong>Job title:</strong> <%= @contact.job_title %> </p>
	<p> <strong>Organization:</strong> <%= @contact.organization %> </p>
	<p> <strong>Industry:</strong> <%= @contact.industry %> </p>
	<p> <strong>Country:</strong> <%= @contact.country %> </p>

	<p> <strong>About:</strong> <%= @contact.about %> </p>
	<p> <strong>Education:</strong> <%= @contact.education.gsub("\n", "<br/><br/>").html_safe if @contact.education %> </p>
	<p> <strong>Work:</strong> <%= @contact.work.gsub("\n", "<br/><br/>").html_safe if @contact.work %> </p>
</div>
<%#= link_to 'Edit', edit_contact_path(@contact) %>
<%#= link_to 'Back', contacts_path %>